const newsLogData = {
    newssiteLogos: {
        "indiatvnews": "https://lh3.googleusercontent.com/OVqng4wcwcfJNUJSl702U0HdHxScvqzKnYGqp_jpyjKJNPojel1HOS-5fz7GLLV0MTwjMv42yw=h28-rw",
        "indianexpress": "https://lh3.googleusercontent.com/kkBP5GMG7WhGg_OaGvdoYp6jxPdIe5_HE4NLhmd8-80hpps2K2BcHM47_XxnxBo9ub0jbx1ZZQ=h28-rw",
        "ndtv": "https://lh3.googleusercontent.com/tdxgqIuMCdYXjnxBEi-22G1al2_n0slQR4vppoxUyB3fupq2sPqxL3okZNKW_QWJrymCWx6k_g=h24-rw",
        "indiatoday": "https://seeklogo.com/images/I/india-today-logo-0218513CB5-seeklogo.com.png",
        "twitter": "https://www.freepnglogos.com/x-logo-twitter-transparent-logo-download-3.png",
        "koo": "https://hindubabynames.info/downloads/wp-content/themes/hbn_download/download/social-media/koo-app-logo.png",
        "tribuneindia": "https://lh3.googleusercontent.com/htQFG9JPZaFUa_qcdnscLxCGmYkl9Nw3wQ5QEZaJ6jY2OIhqhM1NmN1lGR20f6qtRvw75epuZQ=rw-p",
        "timesofindia": "https://lh3.googleusercontent.com/d9mz-OKghOQPsgxRv1BQzQAI44ifiA_6aAk-gRwo4_32mZXM-TSd5vIY1rL1P2LUH9mFQPnUSRE=h28-rw",
        "timesofindia.indiatimes": "https://lh3.googleusercontent.com/d9mz-OKghOQPsgxRv1BQzQAI44ifiA_6aAk-gRwo4_32mZXM-TSd5vIY1rL1P2LUH9mFQPnUSRE=h28-rw",

        "theguardian": "https://lh3.googleusercontent.com/SU8FywVNtcrG-wgjvZ_0D1-3JR_pN9LNSgjULFH74N748KVyEdkF1jdbvP4Lr7_ClbPZxL-iPw=h28-rw",
        "thewire": "https://lh3.googleusercontent.com/SSPOhuz7pCkiABHOpXnTd8q2LLkKnMDv7JsN6olY9mSmneEgn61u2HPiPChjnzIcUQXAv9gHQ3U=h28-rw",
        "timesnownews": "https://lh3.googleusercontent.com/xzPt0e97Ja5Gt8DehLhtbIKrlbEYv3BFqYGMvpTfcEPQebipShnBjy2NtGUYGqhdfdVHiJTCDA=h28-rw",
        "newindianexpress": "https://lh3.googleusercontent.com/kgbLvIIdD8h7bU8u3O_95yO8u3_xQn0f_K2Fa9qveRWXZHeGj3jlJY5P_8Ht53mcIz5qwIK5mg=h28-rw",
        "india": "http://static.businessworld.in/article/article_large_image/1461587703_sJrvhp_Brand_India.com-_289.png",
        "zeenews": "https://lh3.googleusercontent.com/P5vKcqHxbTjjMEaSjW3C1GRPO79qiHDGtp7i6oGtkWPZ9qLDhYScK7Hwt4xqYs_3k58wRujHL2E=h28-rw",
        "bollywoodlife": "https://lh3.googleusercontent.com/EdiEAhu4d-Vuzh-Dp_QYzsrYT7vFu-G0ovdyK87ob8Ie93jl3JizpgTo-hLt4w_1WaScf2LgcQ=h28-rw",
        "filmfare": "https://lh3.googleusercontent.com/proxy/GO-l3HIkzrlRkAvghcpeaZDsX_tef3xdU_IsmbzSCNzTFhnkQRzyyz-5GpXGMVwejKtaLn39DIbBAfTt539D7CMcjnf6zXhX7fCwYuX8Davo3BtTQw7QVGABWTh5Stbk5ktMDlUodX6oI6L7lgnpcrKRULeIETsehF3_cSGysSQpvHkp8UA7qqXi8k74=h28-rw",
        "cricbuzz": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Cricbuzz_Logo.png",
        "onmanorama": "https://lh3.googleusercontent.com/CQu1snjiWSxybLGkDHMRxTfXDhYHoHn4jKhSS4SwtBcvBx0072D5sjVpw-esbPfHyyIPTBl4FTw=h28-rw",
        "business-standard": "https://lh3.googleusercontent.com/25AdZql8C8Eh8kDECCtzFE4He0-hP9dFQ52UppO5SW6Lto_AVulUZjR1sEBi0pazbjh4K1aqvg=h28-rw",
        "businessinsider": "https://lh3.googleusercontent.com/0Z_qIPcXAZ-56MLgO89VOI-Xt7vE1vgf-gBB3V_gk9mWnJOid3AtZMBk26jLZbjEcgiez77F=h28-rw",
        "opindia": "https://lh3.googleusercontent.com/NshSebJ04FcAuCXoS3AoGztt_6EFCnRpESMbMmzWEvdluJy7zqe7uhibn2HC2G_8HGh5eCE07JA=h28-rw",
        "dnaindia": "https://lh3.googleusercontent.com/G2KZIntNftmv-PAdzkbpVtP9klOT7CEsOzEu2Ke7HVC0FZXHw2U4SVJZl-xac-wfAeFe05LJZQ=h28-rw",
        "telegraphindia": "https://lh3.googleusercontent.com/uUe0FJ8TnJuVj0_1dipVQCIdiYmczngQGF0szNSYBqfGr5PVRLQNbwZBzG1gyZT2LgZtPAoCxQ=h28-rw",
        "economictimes": "https://lh3.googleusercontent.com/b4pBtwVcE9sFMZU0IN0VtW48iY0Gda44mzY-zfHtpsxojlwqHbrR8W4szlDSytsF5L15Wqy8=h28-rw",
        "economictimes.indiatimes": "https://lh3.googleusercontent.com/b4pBtwVcE9sFMZU0IN0VtW48iY0Gda44mzY-zfHtpsxojlwqHbrR8W4szlDSytsF5L15Wqy8=h28-rw",
        "thehindu": "https://lh3.googleusercontent.com/s1DVQ3k55HNu7lvn46aiRsiBFDECXxzIF-rHRjb-tiiuFLHcSKUTP6Qq_WbT_qMHYDnZUnuW=h28-rw",
        "cricketaddictor": "https://lh3.googleusercontent.com/6zpG-kiun7YtRTum9gx_K2wknzs8yYHkrXBAoRRdBKXU6TYHudQ9nS9t_0ErgqllO5F5GHqa=h28-rw",
        "slate": "https://lh3.googleusercontent.com/94JAwcC4pcaIUFkMrK9fOV1csEH8fqaNzo-j0j6pUkN7K4xLfvnJOUmxbtcNEj4ij7sQjfr26q6OwYxZfQs=h48-rw",
        "thenewsminute": "https://media.glassdoor.com/sqll/4402561/the-news-minute-squarelogo-1627044608667.png",
        "theprint": "https://lh3.googleusercontent.com/haO6a652o2FAsyhyEPHevk4BGBw8m-El3DJNqMgwfIPjKF7TWXmhK-FXZzl-tqD9sH6nci6bYA=h28-rw",
        "livemint": "https://lh3.googleusercontent.com/JufTzTMu9l6RFyXEEfl6ZPdS7xjYhoSXVmDHURyphjVSNK2zH8uWdyJKd9gg0YOYUCop4Alylis=h28-rw",
        "deccanherald": "https://lh3.googleusercontent.com/vx6XRVNJWUlNOJ3yf1IzadkFok5xsOVLj6KyxSazaJpeS3nMoRdtRNuZAQZh_2zBWfdBl08EpA=h28-rw",
        "fitstpost": "https://lh3.googleusercontent.com/k7siJQMJMgu5AcfU4N_7C-2cg_j4eaVTGnPnICIsOALqS7pM3U2ZwsNrGrNdCGabqa6ZzPVb=h28-rw",
        "outlook": "https://lh3.googleusercontent.com/wIl0x7Zn5G_lHtDakJqH_60UHFFPO8dPczHUAOuze0CUTZeYAC-azft1T8wRc-M1dQ2pTT2b=h28-rw",
        "english.mathrubhumi": "https://lh3.googleusercontent.com/wSMBAxZMEXN3oRMSazcVyW4yVIzoZYc8s1IIFqYCjPmx-wEPq_h7GbDnLbu4dpMrn2kNcsaxnQ=rw-p",
        "rediff": "https://upload.wikimedia.org/wikipedia/commons/9/90/Rediff-logo.png?20190520130226",
        "barandbench": "https://images.assettype.com/barandbench/2019-12/7a743b15-5d5d-44d7-96c2-13616780ed95/brand_2x.png",
        "swarajyamag": "https://tma-live.s3.ap-south-1.amazonaws.com/medias/58b3b6790a7252339acdf10b/1565808839188/81804119eba1dd9d2378d70364c27a56.PNG",
        "inshorts": "https://assets.inshorts.com/website_assets/images/logo_inshorts.png",
        "businesstoday": "https://i0.wp.com/www.speakin.co/edit/wp-content/uploads/2019/05/Business-Today-Logo.png",
        "nytimes": "https://e7.pngegg.com/pngimages/943/568/png-clipart-banana-skirt-productions-the-new-york-times-logo-business-newspaper-new-york-icons-text-logo.png",
        "9news": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/9news-logo.svg/1280px-9news-logo.svg.png",

        "bbc": "https://w7.pngwing.com/pngs/850/1001/png-transparent-computer-icons-logo-of-the-bbc-bbc-world-news-uc-browser-text-rectangle-logo-thumbnail.png",
        "hindustantimes": "https://www.hindustantimes.com/res/images/logo.png",
        "moneycontrol": "https://play-lh.googleusercontent.com/qTe9gNn4oQ_TRLtVqWBr_CeqXqcSMniRo1kZOUKLcK0huJ6V3qL6ibEOnK6Xls1k4Rg",
        "thehindubusinessline": "https://assets-global.website-files.com/61729c38b42c4bffd6cf271e/6175167c192a76dc177abb4d_60210f51870298bd63c073d9_logo%2520(2).png",
        "news18": "https://seeklogo.com/images/N/news18-network-logo-A2974508F9-seeklogo.com.png",

        "greaterkashmir": "https://gumlet.assettype.com/greaterkashmir/2021-05/c34229b4-703a-4b01-a0c0-7d418d5d3a8e/PrimaryLogo.png?w=1400&dpr=2.0",
        "aninews": "https://play-lh.googleusercontent.com/5bk0o45-D1jBO6muvhjpSGC4wTvn5tok2JLC-YW4jHYjXmzySfazIRqMaLV-L4gAKbZp",
        "firstpost": "https://upload.wikimedia.org/wikipedia/commons/a/af/Firstpost.com_Logo.png",
        "wionews": "https://foggymedia.in/media/static/news_logos/wion.png",
        "theweek": "https://img.theweek.in/content/dam/week/logo/The-Week-Logo-Big.png",
        "freepressjournal": "https://upload.wikimedia.org/wikipedia/commons/0/09/The_Free_Press_Journal_logo.jpg",
        "news.sky": "https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Sky_News_logo.svg/2560px-Sky_News_logo.svg.png",
        "apnews": "https://w7.pngwing.com/pngs/628/114/png-transparent-associated-press-digital-journalism-journalist-news-ap-logo-text-trademark-logo.png",
        "edition.cnn": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/CNN_International_logo.svg/2048px-CNN_International_logo.svg.png",
        "dsij": "https://www.dsij.in/Portals/0/logo_dalalstreet.png?ver=YfhTR89EaxvmgcthBdW5jQ%3d%3d",
        "financialexpress": "https://www.thetamara.com/wp-content/uploads/2022/06/financial-express-logo.png",
        "telecom.economictimes.indiatimes": "https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/3f/c6/42/3fc6422a-0457-373f-c000-905f33973507/ETTelecomAppIcon-1x_U007emarketing-0-4-0-85-220.png/1200x600wa.png",
        "cnbctv18": "https://w7.pngwing.com/pngs/577/17/png-transparent-india-cnbc-tv18-television-channel-india-television-text-heart.png",
        "gadgetsnow": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Gadgets_Now_logo.jpg",
        "gadgets360": "https://cdn.gadgets360.com/gadgets360_logo.png",
        "tech.hindustantimes": "https://tech.hindustantimes.com/ht/tech/static/revamp/images/png/Httech-logo-transparent.png",
        "sparrowsnews": "https://sparrowsnews.com/wp-content/uploads/2020/09/wp-15996733763111656929577038820433.png",
        "cnet": "https://e7.pngegg.com/pngimages/910/677/png-clipart-c-net-logo-cnet-logo-icons-logos-emojis-tech-companies.png",
        "extremetech": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/ExtremeTech_logo.svg/2560px-ExtremeTech_logo.svg.png",
        "thequint": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/The_Quint_logo_with_purple_background.svg/640px-The_Quint_logo_with_purple_background.svg.png",
        "sportskeeda": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Sportskeeda.svg/1280px-Sportskeeda.svg.png",
        "afkgaming": "https://assets.entrepreneur.com/content/3x2/2000/1600351826-WhatsAppImage2020-09-17at72641PM.jpeg",
        "pinkvilla": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/PinkVilla_Logo.png/800px-PinkVilla_Logo.png",
        "indiaglitz": "https://d1pyuwmru9u39x.cloudfront.net/images/white_iglogo.png",
        "indiatimes": "https://seeklogo.com/images/I/indiatimes-logo-AACB2D2AE7-seeklogo.com.png",
        "123telugu": "https://gallery.123telugu.com/images/logo/123_logo_Mallemaala.png",
        "sports.ndtv": "https://drop.ndtv.com/homepage/ndtv_sports/images/ndtv_sports1200x630.png",
        "espncricinfo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/ESPNCricinfo.png/1200px-ESPNCricinfo.png",
        "sportstar.thehindu": "https://play-lh.googleusercontent.com/1Y7NTKrcvj7c6NIgoJJIcUyl_M8ErgS1LGMo-4YCuO7W54mwxdxlWC7S7hbb5s-PnZo",
        "khelnow": "https://assets-webp.khelnow.com/news/uploads/2022/01/KN_Outline_Logo-copy-1024x724.png.webp",
        "espn": "https://e7.pngegg.com/pngimages/877/31/png-clipart-bristol-espn-inc-roku-watchespn-betis-television-text.png",
        "crictracker": "https://www.crictracker.com/images/CricTracker-Facebook-Preview.jpg",
        "thestatesman": "https://www.thestatesman.com/wp-content/themes/statesmantheme/images/the-statesman-logo-new.png",
        "zeenews.india": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Zee_news.svg/2560px-Zee_news.svg.png",
        "cricket.one": "https://play-lh.googleusercontent.com/f5_w5_hXyQUd0eBgavdNY96Z7V76DcyuKSFO26Z57DPFiQDePmaRrK6ijfhNgmf3Mkc",
        "weather": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/The_Weather_Channel_logo_2005-present.svg/1200px-The_Weather_Channel_logo_2005-present.svg.png",
        "interestingengineering": "https://upload.wikimedia.org/wikipedia/commons/0/07/Interesting_Engineering.jpg",
        "cbsnews": "https://w7.pngwing.com/pngs/401/965/png-transparent-cbs-news-logo-television-news-miscellaneous-television-text.png",
        "jpost": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Jerusalem_Post_Logo.svg/1200px-Jerusalem_Post_Logo.svg.png",
        "petapixel": "https://getlogovector.com/wp-content/uploads/2021/07/petapixel-logo-vector.png",
        "newsweek": "https://www.liblogo.com/img-logo/ne3089n9b2-newsweek-logo-newsweek-logo-download-vector.png",
        "cyprus-mail": "https://cyprus-mail.com/wp-content/uploads/2021/12/cropped-CMlogo.png",
        "dhakatribune": "https://ecdn.dhakatribune.net/contents/themes/public/style/images/logo-en.png",
        "healio": "https://mma.prnewswire.com/media/1056257/Healio_Logo.jpg",
        "timesofoman": "https://upload.wikimedia.org/wikipedia/en/b/b0/Times_of_Oman_logo.jpg",
        "daijiworld": "https://www.daijiworld.com/images/daijiworldLogo1.jpg",
        "livelaw": "https://www.livelaw.in/images/logo.png?v=7",
        "newsclick": "https://mc.webpcache.epapr.in/mcms.php?size=large&in=https://mcmscache.epapr.in/post_images/website_350/post_34985437/full.png",
        "aljazeera": "https://e7.pngegg.com/pngimages/701/785/png-clipart-al-jazeera-english-al-jazeera-documentary-channel-al-jazeera-media-network-news-arabic-calligraphy-television-text.png",
        "theshillongtimes": "https://theshillongtimes.com/wp-content/uploads/2023/08/Tst-logo-300x34.png",
        "eurasiantimes": "https://www.eurasiantimes.com/wp-content/uploads/2018/05/EurAsianTimes.png",
        "fxstreet": "https://play-lh.googleusercontent.com/OXoAaY67c0lVl_gaoKuGx1-yInAGGgRHWBlP8LwQr8XwAbH6V3j8KUeFfQ5abWy0Spg",
        "gsmarena": "https://fdn.gsmarena.com/vv/assets12/i/logo-fallback.gif",
        "tomsguide": "https://e7.pngegg.com/pngimages/813/101/png-clipart-technology-business-tom-s-hardware-logo-tom-s-guide-dont-share.png",
        "sammobile": "https://www.sammobile.com/wp-content/themes/sammobile-5/assets/img/logo.png",
        "mysmartprice": "https://assets.mspimages.in/logos/mysmartprice/owl/blue@2x.png",
        "editorji": "https://res.9appsinstall.com/group5/M02/94/91/IaEHAF3Pt9uAXI5mAAAhFQK-GqY372.png?x-oss-process=style/mq200",
        "english.varthabharati": "https://english.varthabharati.in/images/logo.png",
        "thebridge": "https://thebridge.in/images/logo.png",
        "greatandhra": "https://yt3.ggpht.com/ytc/AKedOLS5UdubuMt0J1qR-S8uoEO7YjjzQ5RngbxSrywDAA=s900-c-k-c0x00ffffff-no-rj?tenant=sc&referrer=pwa-sharechat-service&f=ffff-no-rj",
        "science.thewire": "https://cdn.thewire.in/wp-content/uploads/2020/02/20162750/Union.png",
        "theconversation": "https://upload.wikimedia.org/wikipedia/commons/8/85/The_Conversation_logo.png",
        "phys": "https://phys.b-cdn.net/tmpl/v6/img/logo-header.png",
        "themessenger": "https://themessenger.com/defaultMessenger.jpg",
        "thehealthsite": "https://www.protinex.com/wp-content/uploads/2020/05/health-site-logo.png",
        "usatoday": "https://w7.pngwing.com/pngs/33/654/png-transparent-united-states-usa-today-logo-newspaper-united-states-blue-text-logo.png",
        "punekarnews": "https://www.punekarnews.in/wp-content/uploads/2015/10/cropped-Punekar-News-App11.png",
        "mypunepulse": "https://www.mypunepulse.com/wp-content/uploads/2023/08/punepulse-logo.webp",
        "mid-day": "https://www.mid-day.com/images/mid-day-admin.jpg",
        "indiaeducationdiary": "https://indiaeducationdiary.in/wp-content/uploads/2022/08/indiaeducationdiarylogo_header.png",
        "economist": "https://e7.pngegg.com/pngimages/355/504/png-clipart-the-economist-logo-economist-group-magazine-organization-others-miscellaneous-company.png",
        "arabnews": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Arab_News_%282019-07-27%29.svg/1200px-Arab_News_%282019-07-27%29.svg.png",
        "zeebiz": "https://cdn.zeebiz.com/html/images/zee-business.png",
        "moneylife": "https://play-lh.googleusercontent.com/NRcK-VCd2ReV3VXTvtbI4s0JsNOtVhFueKQe3onh-EYw2gYOoYpOxm0miu1Z7v1jiR4",
        "digitaltrends": "https://w7.pngwing.com/pngs/11/496/png-transparent-logo-digital-trends-font-brand-graphics-dolby-atmos-blue-text-logo.png",
        "m.rediff": "https://upload.wikimedia.org/wikipedia/commons/9/90/Rediff-logo.png?20190520130226",
        "sportstiger": "https://www.iismworld.com/wp-content/uploads/2021/04/sports-tiger-final-logo-1.png",
        "nature": "https://w7.pngwing.com/pngs/477/64/png-transparent-springer-nature-publishing-research-science-science-text-logo-publishing.png",
        "washingtonpost": "https://e7.pngegg.com/pngimages/29/69/png-clipart-washington-d-c-the-washington-post-1st-option-safety-services-ltd-news-logo-hi-turn-the-court-miscellaneous-text-thumbnail.png",
        "food.ndtv": "https://food.ndtv.com/static/web/images/food_logo_112x112.png",

        "timesofisrael": "https://play-lh.googleusercontent.com/5RXKeNxLAMc60xycN3PSvoxwEY8Pp9iiZH2stMxmh9YoL6YOa7wSYPMA-w1vpYM7rg",
        "udayavani": "https://www.udayavani.com/wp-content/uploads/2021/09/Udayavani-English-New-logo.png",
        "goodreturns": "https://www.goodreturns.in/images/goodreturns-og-image.jpg",
        "thehansindia": "https://www.thehansindia.com/images/logo.png?v=2",
        "bqprime": "https://images.assettype.com/bloombergquint/2022-04/26eb2ecf-4c78-45e5-b368-24961274ca85/bq_prime___b.png",
        "in.mashable": "https://e7.pngegg.com/pngimages/465/91/png-clipart-logo-itz-cash-brand-product-design-mashable-logo-itz-cash.png",
        "91mobiles": "https://www.91-cdn.com/hub/wp-content/uploads/2021/03/logo-169x45-white.png",
        "beebom": "https://beebom.com/wp-content/uploads/2016/10/Beebom-Logo-Icon.png",
        "gulte": "https://cdn.gulte.com/wp-content/uploads/2021/01/gulte-logo-schema.png",
        "english.jagran": "https://seeklogo.com/images/J/jagran-logo-A06AC1B413-seeklogo.com.png",
        "wral": "https://images.wral.com/asset/podcasts/2019/05/02/18361859/WRALNewsDaily1920x1080-DMID1-5m0ymhfus-640x360.jpg",
        "hcplive": "https://cdn.sanity.io/images/0vv8moc6/hcplive/09f00492e5df5f66a0d97f316f6d3704619ba791-1054x146.png",
        "bollywoodhungama": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Bollywood_Hungama_logo.svg/800px-Bollywood_Hungama_logo.svg.png",
        "deccanchronicle": "https://e7.pngegg.com/pngimages/449/114/png-clipart-deccan-chronicle-holdings-limited-deccan-chronicle-holdings-ltd-newspaper-the-asian-age-diwali-crackers-text-logo-thumbnail.png",
        "m9": "https://www.m9.news/wp-content/themes/m9-new/assets/img/logo_v12.png",
        "tracktollywood": "https://pbs.twimg.com/profile_images/1267077190182531074/4hnAEbjC_400x400.jpg",
        "tv9hindi": "https://static.wikia.nocookie.net/logopedia/images/3/36/TV9_Bharatvarsh.jpg",
        "jagran": "https://seeklogo.com/images/J/jagran-logo-A06AC1B413-seeklogo.com.png",
        "navbharattimes": "https://seeklogo.com/images/N/nbt-nav-bharat-times-logo-25D9D9A9C3-seeklogo.com.png",
        "reuters": "https://upload.wikimedia.org/wikipedia/commons/0/09/Reuters_TV_logo.png",
        "nagpurtoday": "https://www.nagpurtoday.in/wp-content/uploads/2022/01/nt-newlogo-1.png",


        "telanganatoday": "https://w7.pngwing.com/pngs/86/397/png-transparent-bogatha-waterfall-doconline-health-india-private-limited-telangana-today-business-eventsnow-pvt-ltd-telangana-text-logo-monochrome.png",
        "news.abplive": "https://static.businessworld.in/article/article_extra_large_image/1608102156_IGOImt_new_abp_logo.jpg",
        "hindi.news18": "https://ww2.freelogovectors.net/wp-content/uploads/2022/01/news18logo-freelogovectors.net_.png",
        "navbharattimes.indiatimes": "https://static.wikia.nocookie.net/logopedia/images/0/03/Navbharat_Times.png",
        "prokabaddi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/919-9198627_the-league-will-continue-its-existing-format-and.png/1200px-919-9198627_the-league-will-continue-its-existing-format-and.png",
        "skymetweather": "https://bestmediainfo.com/uploads/2023/04/1681183102.Skymet-New-Logo-Beyond-Weather.jpg",
        "weatherandradar": "https://www.weatherandradar.in/assets/logos/preview-teaser/en-IN_logo-isobars_16x9.png",
        "lifestyle.livemint": "https://lifestyle.livemint.com/resources/assets/images/home-share-logo-600x330.png",
        "news-medical": "https://upload.wikimedia.org/wikipedia/commons/f/f4/News-Medical_Logo.png",
        "cricket": "https://play-lh.googleusercontent.com/f5_w5_hXyQUd0eBgavdNY96Z7V76DcyuKSFO26Z57DPFiQDePmaRrK6ijfhNgmf3Mkc",

        "news.un": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Logo_of_the_United_Nations.svg/1970px-Logo_of_the_United_Nations.svg.png",
        "techcrunch": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/TechCrunch_logo.svg/2560px-TechCrunch_logo.svg.png",
        "fonearena": "https://images.fonearena.com/blog/wp-content/uploads/2016/06/fonearena-logo.jpg",
        "gizmochina": "https://images.crunchbase.com/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1420363342/jdatwm9zprwndptr1gmj.png",
        "recipes.timesofindia": "https://static.toiimg.com/photo/73660730.cms",
        "vogue": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/VOGUE_LOGO.svg/2560px-VOGUE_LOGO.svg.png",
        "crickettimes": "https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/8f/c9/ad/8fc9ada3-d77f-c28a-dcb3-d1baa06a957c/AppIcon-0-1x_U007emarketing-0-0-85-220-6.png/1200x630wa.png",
        "thecricketer": "https://admin.thecricketer.com/weblab/sites/96c8b790-b593-bfda-0ba4-ecd3a9fdefc2/resources/images/site/thecricketer.png",
        "independent.co": "https://e7.pngegg.com/pngimages/275/239/png-clipart-the-independent-logo-newspaper-brand-alex-ferguson-company-text.png",
        "san": "https://is5-ssl.mzstatic.com/image/thumb/Purple126/v4/0f/25/18/0f2518e0-49d6-30ed-7874-0635fc2dd5b2/AppIcon-1x_U007emarketing-0-5-0-85-220.png/200x200bb.jpg",
        "popsci": "https://www.popsci.com/uploads/2023/03/21/PopSci_LogoStacked_Black_s.png",
        "inverse": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Inverse_logo_2020.svg/1280px-Inverse_logo_2020.svg.png",
        "scitechdaily": "https://scitechdaily.com/images/scitechdaily-logo-flat-100.png",
        "bangkokpost": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/BangkokPost.svg/2560px-BangkokPost.svg.png",
        "www3.nhk.or": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/NHK_World-Japan_TV.svg/2560px-NHK_World-Japan_TV.svg.png",
        "kitchener.citynews": "https://kitchener.citynews.ca/wp-content/blogs.dir/sites/3/2023/04/25/CityNews-Org-Schema-Logo.jpg",
        "medscape": "https://img.medscapestatic.com/pi/logos/mscp-logo.png",
        "fiercepharma": "https://qtxasset.com/quartz/qcloud5/media/image/fiercepharma/1591304531/Fierce-Pharma.jpg/Fierce-Pharma.jpg",
        "eastmojo": "https://i0.wp.com/www.eastmojo.com/wp-content/uploads/2021/02/east-mojo-logo.png",


        "amarujala": "https://upload.wikimedia.org/wikipedia/commons/d/d2/Amar_Ujala_Logo.png",
        "jansatta": "https://1.bp.blogspot.com/-sBWWNN3q38w/WC1RNJ4ox5I/AAAAAAAAQnM/Tkin3U83BzkbpiajPWb92Mn-VB7JIUYRwCLcB/w1200-h630-p-k-no-nu/jansatta.jpg",
        "livehindustan": "https://images.livehindustan.com/uploadimage/images/hh_logo.png",
        "yourstory": "https://asset.brandfetch.io/idZ6zCbLkU/id1A_ZHX5y.png",
        "vccircle": "https://www.schoolmitra.com/assets/site_v5/vccircle_logo-rbg.png",
        "theverge": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/The_Verge_wordmark_2022.svg/1200px-The_Verge_wordmark_2022.svg.png",
        "insidesport": "https://hindi.insidesport.in/wp-content/uploads/2021/04/InsideSport-Small-Dark-logo.png",
        "dawn": "https://www.dawn.com/_img/logo.png",
        "bgr": "https://bgr.com/wp-content/uploads/2021/06/BGR-logo-black.png",
        "universetoday": "https://www.universetoday.com/wp-content/uploads/2020/10/cropped-cleanutlogo-1.png",
        "space": "https://forums.space.com/styles/space/space/space-logo-black.png",
        "healthshots": "https://exchange4media.gumlet.io/news-photo/104960-healthshots.jpg",
        "kalingatv": "https://kalingatv.com/wp-content/uploads/2022/10/Ktv-Logo_.png",
        "odishabytes": "https://odishabytes.com/wp-content/uploads/2019/11/OB-FInal-Logo1_300wNewDesign.png",
        "deseret": "https://cdn.vox-cdn.com/uploads/chorus_asset/file/18933316/Deseret_News_black__yellow_period.png",
        "kxan": "https://upload.wikimedia.org/wikipedia/commons/0/0d/KXAN_Austin_News_logo.png",
        "bronx.news12": "https://images.squarespace-cdn.com/content/v1/58bddd12e58c6278e8a670e2/1597159459277-S9PPFVNBJCSSJKB90GGF/new12bronx.png",
        "stamfordadvocate": "https://storage.googleapis.com/hnp-subscription-app-static-files/casper_footer/CT_AD.png",
        "bmcpublichealth.biomedcentral": "https://healthsystemsresearch.org/hsr2018/wp-content/uploads/2018/01/BMC-Logo.png",
        "medicalxpress": "https://medx.b-cdn.net/tmpl/v6/img/logo.png"












    },


}

const headlineLogoObject = newsLogData.newssiteLogos;

module.exports = headlineLogoObject
